Landing page updates
bikespace/bikespace pull request #106
Opened 2024-02-06 03:00 UTC by tallcoleman

Various edits to the BikeSpace landing page to ensure the content is more up to date. Main changes:

- Updated old/stale content in various sections
- Updated dashboard image and removed un-needed site assets
- Removed inactive social media links
- Added click to load for parking map which prevents unintentional zooming on scroll and improves analytics understanding of how many users are using the map
- Addressed a number of accessibility issues, including improvements to text and background contrast as well as indicating that images are for decoration only via empty alt tags

Hero image still unchanged, but can submit another PR for it later

2024-02-07 22:26 UTC, sonalranjit requested changes

2024-02-07 22:26 UTC, sonalranjit commented on bikespace_landing_page/index.html
> +    <!-- <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
we can remove these dead code

2024-02-10 14:20 UTC, tallcoleman commented on bikespace_landing_page/index.html
> +    <!-- <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
removed!

2024-02-10 14:48 UTC, sonalranjit approved these changes
thankss!

2024-02-10 15:50 UTC, merged