Add analytics to dashboard and landing pages
bikespace/bikespace pull request #97
Opened 2024-01-21 15:55 UTC by tallcoleman

Added analytics tracking using Umami

Tracking will only work on production sites - triggered based on checking host URL

## Events tracked for dashboard:

Outbound nav links (to landing page, app, or GitHub)

Popup opened (logs issue id)
e.g. `{ submission_id: 398 }`

Issue chart click (logs filter values)
e.g. `{ issues: { contains: "not_provided" } }`

Day chart click (logs filter values)
e.g. `{ parking_time: { day_index: 4 } }`

Clear filter button click

Note - nested objects are logged in Umami something like this:
```js
{
  field: "issues.contains",
  type: "string",
  value: "not_provided",
}
```

## Events tracked for landing page

Outbound and mailto links

User click on feature in parking map

2024-01-22 14:42 UTC, sonalranjit commented on bikespace_dashboard/index.html
> +        s.src = "https://eu.umami.is/script.js";
The tracking code snippet generated on umami refers to us `https://us.umami.is/script.js` im not sure if it makes a difference, maybe we should keep it to the us.umami.is to keep it consistent with the setup on umami.

2024-01-22 14:43 UTC, sonalranjit commented on bikespace_landing_page/ParkingMap.html
> +      s.src = "https://eu.umami.is/script.js";
Same comment as above, let's use `us.umami.is`

2024-01-22 14:43 UTC, sonalranjit commented on bikespace_landing_page/index.html
> +        s.src = "https://eu.umami.is/script.js";
1 more for the `us.umami.js`

2024-01-22 14:44 UTC, sonalranjit requested changes
Just the comments on the using `us.umami.is` for their script.

2024-01-23 00:05 UTC, tallcoleman reviewed
Trying to resolve the "1 review requesting changes"

2024-01-23 02:43 UTC, sonalranjit approved these changes
looks great

2024-01-23 02:43 UTC, merged